// Generated by scripts/generate-map-labels.mjs. Do not edit manually.
export const mapLabelData = {
  "source": "Natural Earth 1:110m (CC0); Norwegian marine labels from Wikidata",
  "countries": [
    {
      "id": "ARG",
      "isoA2": "AR",
      "nameEn": "Argentina",
      "lat": -33.501159,
      "lon": -64.173331,
      "minZoom": 2,
      "rank": 2
    },
    {
      "id": "AUS",
      "isoA2": "AU",
      "nameEn": "Australia",
      "lat": -24.129522,
      "lon": 134.04972,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "BEL",
      "isoA2": "BE",
      "nameEn": "Belgium",
      "lat": 50.785392,
      "lon": 4.800448,
      "minZoom": 4,
      "rank": 2
    },
    {
      "id": "BRA",
      "isoA2": "BR",
      "nameEn": "Brazil",
      "lat": -12.098687,
      "lon": -49.55945,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "CAN",
      "isoA2": "CA",
      "nameEn": "Canada",
      "lat": 60.324287,
      "lon": -101.9107,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "CHL",
      "isoA2": "CL",
      "nameEn": "Chile",
      "lat": -38.151771,
      "lon": -72.318871,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "COL",
      "isoA2": "CO",
      "nameEn": "Colombia",
      "lat": 3.373111,
      "lon": -73.174347,
      "minZoom": 3,
      "rank": 2
    },
    {
      "id": "COD",
      "isoA2": "CD",
      "nameEn": "Democratic Republic of the Congo",
      "lat": -1.858167,
      "lon": 23.458829,
      "minZoom": 2,
      "rank": 2
    },
    {
      "id": "EGY",
      "isoA2": "EG",
      "nameEn": "Egypt",
      "lat": 26.186173,
      "lon": 29.445837,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "ETH",
      "isoA2": "ET",
      "nameEn": "Ethiopia",
      "lat": 8.032795,
      "lon": 39.0886,
      "minZoom": 2,
      "rank": 2
    },
    {
      "id": "FRA",
      "isoA2": "FR",
      "nameEn": "France",
      "lat": 46.696113,
      "lon": 2.552275,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "DEU",
      "isoA2": "DE",
      "nameEn": "Germany",
      "lat": 50.961733,
      "lon": 9.678348,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "IND",
      "isoA2": "IN",
      "nameEn": "India",
      "lat": 22.686852,
      "lon": 79.358105,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "IDN",
      "isoA2": "ID",
      "nameEn": "Indonesia",
      "lat": -0.954404,
      "lon": 101.892949,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "IRN",
      "isoA2": "IR",
      "nameEn": "Iran",
      "lat": 32.166225,
      "lon": 54.931495,
      "minZoom": 2,
      "rank": 2
    },
    {
      "id": "ITA",
      "isoA2": "IT",
      "nameEn": "Italy",
      "lat": 44.732482,
      "lon": 11.076907,
      "minZoom": 2,
      "rank": 2
    },
    {
      "id": "JPN",
      "isoA2": "JP",
      "nameEn": "Japan",
      "lat": 36.142538,
      "lon": 138.44217,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "KEN",
      "isoA2": "KE",
      "nameEn": "Kenya",
      "lat": 0.549043,
      "lon": 37.907632,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "MEX",
      "isoA2": "MX",
      "nameEn": "Mexico",
      "lat": 23.919988,
      "lon": -102.289448,
      "minZoom": 2,
      "rank": 2
    },
    {
      "id": "NZL",
      "isoA2": "NZ",
      "nameEn": "New Zealand",
      "lat": -39.759,
      "lon": 172.787,
      "minZoom": 2,
      "rank": 2
    },
    {
      "id": "NGA",
      "isoA2": "NG",
      "nameEn": "Nigeria",
      "lat": 9.439799,
      "lon": 7.50322,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "PAK",
      "isoA2": "PK",
      "nameEn": "Pakistan",
      "lat": 29.328389,
      "lon": 68.545632,
      "minZoom": 2,
      "rank": 2
    },
    {
      "id": "PNG",
      "isoA2": "PG",
      "nameEn": "Papua New Guinea",
      "lat": -5.695285,
      "lon": 143.910216,
      "minZoom": 2,
      "rank": 2
    },
    {
      "id": "CHN",
      "isoA2": "CN",
      "nameEn": "People's Republic of China",
      "lat": 32.498178,
      "lon": 106.337289,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "PER",
      "isoA2": "PE",
      "nameEn": "Peru",
      "lat": -12.976679,
      "lon": -72.90016,
      "minZoom": 2,
      "rank": 2
    },
    {
      "id": "PHL",
      "isoA2": "PH",
      "nameEn": "Philippines",
      "lat": 11.198,
      "lon": 122.465,
      "minZoom": 2,
      "rank": 2
    },
    {
      "id": "PRT",
      "isoA2": "PT",
      "nameEn": "Portugal",
      "lat": 39.606675,
      "lon": -8.271754,
      "minZoom": 3,
      "rank": 2
    },
    {
      "id": "RUS",
      "isoA2": "RU",
      "nameEn": "Russia",
      "lat": 58.249357,
      "lon": 44.686469,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "SAU",
      "isoA2": "SA",
      "nameEn": "Saudi Arabia",
      "lat": 23.806908,
      "lon": 44.6996,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "ZAF",
      "isoA2": "ZA",
      "nameEn": "South Africa",
      "lat": -29.708776,
      "lon": 23.665734,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "KOR",
      "isoA2": "KR",
      "nameEn": "South Korea",
      "lat": 36.384924,
      "lon": 128.129504,
      "minZoom": 2,
      "rank": 2
    },
    {
      "id": "ESP",
      "isoA2": "ES",
      "nameEn": "Spain",
      "lat": 40.090953,
      "lon": -3.464718,
      "minZoom": 2,
      "rank": 2
    },
    {
      "id": "TUR",
      "isoA2": "TR",
      "nameEn": "Turkey",
      "lat": 39.345388,
      "lon": 34.508268,
      "minZoom": 2,
      "rank": 2
    },
    {
      "id": "GBR",
      "isoA2": "GB",
      "nameEn": "United Kingdom",
      "lat": 54.402739,
      "lon": -2.116346,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "USA",
      "isoA2": "US",
      "nameEn": "United States of America",
      "lat": 39.538479,
      "lon": -97.482602,
      "minZoom": 1,
      "rank": 2
    },
    {
      "id": "VNM",
      "isoA2": "VN",
      "nameEn": "Vietnam",
      "lat": 21.715416,
      "lon": 105.387292,
      "minZoom": 2,
      "rank": 2
    },
    {
      "id": "AFG",
      "isoA2": "AF",
      "nameEn": "Afghanistan",
      "lat": 34.164262,
      "lon": 66.496586,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "DZA",
      "isoA2": "DZ",
      "nameEn": "Algeria",
      "lat": 27.397406,
      "lon": 2.808241,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "AGO",
      "isoA2": "AO",
      "nameEn": "Angola",
      "lat": -12.182762,
      "lon": 17.984249,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "BGD",
      "isoA2": "BD",
      "nameEn": "Bangladesh",
      "lat": 24.214956,
      "lon": 89.684963,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "BOL",
      "isoA2": "BO",
      "nameEn": "Bolivia",
      "lat": -16.666015,
      "lon": -64.593433,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "BFA",
      "isoA2": "BF",
      "nameEn": "Burkina Faso",
      "lat": 12.673048,
      "lon": -1.36388,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "KHM",
      "isoA2": "KH",
      "nameEn": "Cambodia",
      "lat": 12.647584,
      "lon": 104.50487,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "CMR",
      "isoA2": "CM",
      "nameEn": "Cameroon",
      "lat": 4.585041,
      "lon": 12.473488,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "TCD",
      "isoA2": "TD",
      "nameEn": "Chad",
      "lat": 15.142959,
      "lon": 18.645041,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "CUB",
      "isoA2": "CU",
      "nameEn": "Cuba",
      "lat": 21.334024,
      "lon": -77.975855,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "ECU",
      "isoA2": "EC",
      "nameEn": "Ecuador",
      "lat": -1.259076,
      "lon": -78.188375,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "FIN",
      "isoA2": "FI",
      "nameEn": "Finland",
      "lat": 63.252361,
      "lon": 27.276449,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "GHA",
      "isoA2": "GH",
      "nameEn": "Ghana",
      "lat": 7.717639,
      "lon": -1.036941,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "GRC",
      "isoA2": "GR",
      "nameEn": "Greece",
      "lat": 39.492763,
      "lon": 21.72568,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "GRL",
      "isoA2": "GL",
      "nameEn": "Greenland",
      "lat": 74.319387,
      "lon": -39.335251,
      "minZoom": 1,
      "rank": 3
    },
    {
      "id": "GTM",
      "isoA2": "GT",
      "nameEn": "Guatemala",
      "lat": 14.982133,
      "lon": -90.497134,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "GIN",
      "isoA2": "GN",
      "nameEn": "Guinea",
      "lat": 10.618516,
      "lon": -10.016402,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "ISL",
      "isoA2": "IS",
      "nameEn": "Iceland",
      "lat": 64.779286,
      "lon": -18.673711,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "IRQ",
      "isoA2": "IQ",
      "nameEn": "Iraq",
      "lat": 33.09403,
      "lon": 43.26181,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "IRL",
      "isoA2": "IE",
      "nameEn": "Ireland",
      "lat": 53.078726,
      "lon": -7.798588,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "CIV",
      "isoA2": "CI",
      "nameEn": "Ivory Coast",
      "lat": 7.49139,
      "lon": -5.568618,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "KAZ",
      "isoA2": "KZ",
      "nameEn": "Kazakhstan",
      "lat": 49.054149,
      "lon": 68.685548,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "LBY",
      "isoA2": "LY",
      "nameEn": "Libya",
      "lat": 26.638944,
      "lon": 18.011015,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "MDG",
      "isoA2": "MG",
      "nameEn": "Madagascar",
      "lat": -18.628288,
      "lon": 46.704241,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "MYS",
      "isoA2": "MY",
      "nameEn": "Malaysia",
      "lat": 2.528667,
      "lon": 113.83708,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "MLI",
      "isoA2": "ML",
      "nameEn": "Mali",
      "lat": 18.692713,
      "lon": -2.038455,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "MRT",
      "isoA2": "MR",
      "nameEn": "Mauritania",
      "lat": 19.587062,
      "lon": -9.740299,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "MNG",
      "isoA2": "MN",
      "nameEn": "Mongolia",
      "lat": 45.997488,
      "lon": 104.150405,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "MAR",
      "isoA2": "MA",
      "nameEn": "Morocco",
      "lat": 31.650723,
      "lon": -7.187296,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "MOZ",
      "isoA2": "MZ",
      "nameEn": "Mozambique",
      "lat": -13.94323,
      "lon": 37.83789,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "MMR",
      "isoA2": "MM",
      "nameEn": "Myanmar",
      "lat": 21.573855,
      "lon": 95.804497,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "NAM",
      "isoA2": "NA",
      "nameEn": "Namibia",
      "lat": -20.575298,
      "lon": 17.108166,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "NPL",
      "isoA2": "NP",
      "nameEn": "Nepal",
      "lat": 28.297925,
      "lon": 83.639914,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "NCL",
      "isoA2": "NC",
      "nameEn": "New Caledonia",
      "lat": -21.064697,
      "lon": 165.084004,
      "minZoom": 4,
      "rank": 3
    },
    {
      "id": "NER",
      "isoA2": "NE",
      "nameEn": "Niger",
      "lat": 17.446195,
      "lon": 9.504356,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "PRK",
      "isoA2": "KP",
      "nameEn": "North Korea",
      "lat": 39.885252,
      "lon": 126.444516,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "NOR",
      "isoA2": "NO",
      "nameEn": "Norway",
      "lat": 61.357092,
      "lon": 9.679975,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "POL",
      "isoA2": "PL",
      "nameEn": "Poland",
      "lat": 51.990316,
      "lon": 19.490468,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "ROU",
      "isoA2": "RO",
      "nameEn": "Romania",
      "lat": 45.733237,
      "lon": 24.972624,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "RWA",
      "isoA2": "RW",
      "nameEn": "Rwanda",
      "lat": -1.897196,
      "lon": 30.103894,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "SEN",
      "isoA2": "SN",
      "nameEn": "Senegal",
      "lat": 15.138125,
      "lon": -14.778586,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "SLB",
      "isoA2": "SB",
      "nameEn": "Solomon Islands",
      "lat": -8.029548,
      "lon": 159.170468,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "SDS",
      "isoA2": "SS",
      "nameEn": "South Sudan",
      "lat": 7.230477,
      "lon": 30.390151,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "LKA",
      "isoA2": "LK",
      "nameEn": "Sri Lanka",
      "lat": 7.581097,
      "lon": 80.704823,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "SDN",
      "isoA2": "SD",
      "nameEn": "Sudan",
      "lat": 16.330746,
      "lon": 29.260657,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "SWE",
      "isoA2": "SE",
      "nameEn": "Sweden",
      "lat": 65.85918,
      "lon": 19.01705,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "SYR",
      "isoA2": "SY",
      "nameEn": "Syria",
      "lat": 35.006636,
      "lon": 38.277783,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "TWN",
      "isoA2": "TW",
      "nameEn": "Taiwan",
      "lat": 23.652408,
      "lon": 120.868204,
      "minZoom": 4,
      "rank": 3
    },
    {
      "id": "TZA",
      "isoA2": "TZ",
      "nameEn": "Tanzania",
      "lat": -6.051866,
      "lon": 34.959183,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "THA",
      "isoA2": "TH",
      "nameEn": "Thailand",
      "lat": 15.45974,
      "lon": 101.073198,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "TUN",
      "isoA2": "TN",
      "nameEn": "Tunisia",
      "lat": 33.687263,
      "lon": 9.007881,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "UGA",
      "isoA2": "UG",
      "nameEn": "Uganda",
      "lat": 1.972589,
      "lon": 32.948555,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "UKR",
      "isoA2": "UA",
      "nameEn": "Ukraine",
      "lat": 49.724739,
      "lon": 32.140865,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "UZB",
      "isoA2": "UZ",
      "nameEn": "Uzbekistan",
      "lat": 41.693603,
      "lon": 64.005429,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "VEN",
      "isoA2": "VE",
      "nameEn": "Venezuela",
      "lat": 7.182476,
      "lon": -64.599381,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "YEM",
      "isoA2": "YE",
      "nameEn": "Yemen",
      "lat": 15.328226,
      "lon": 45.874383,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "ZMB",
      "isoA2": "ZM",
      "nameEn": "Zambia",
      "lat": -14.660804,
      "lon": 26.395298,
      "minZoom": 3,
      "rank": 3
    },
    {
      "id": "ZWE",
      "isoA2": "ZW",
      "nameEn": "Zimbabwe",
      "lat": -18.91164,
      "lon": 29.925444,
      "minZoom": 2,
      "rank": 3
    },
    {
      "id": "ATA",
      "isoA2": "AQ",
      "nameEn": "Antarctica",
      "lat": -79.843222,
      "lon": 35.885455,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "AUT",
      "isoA2": "AT",
      "nameEn": "Austria",
      "lat": 47.518859,
      "lon": 14.130515,
      "minZoom": 3,
      "rank": 4
    },
    {
      "id": "BLR",
      "isoA2": "BY",
      "nameEn": "Belarus",
      "lat": 53.821888,
      "lon": 28.417701,
      "minZoom": 3,
      "rank": 4
    },
    {
      "id": "BWA",
      "isoA2": "BW",
      "nameEn": "Botswana",
      "lat": -22.102634,
      "lon": 24.179216,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "BGR",
      "isoA2": "BG",
      "nameEn": "Bulgaria",
      "lat": 42.508785,
      "lon": 25.15709,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "CAF",
      "isoA2": "CF",
      "nameEn": "Central African Republic",
      "lat": 6.989681,
      "lon": 20.906897,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "DNK",
      "isoA2": "DK",
      "nameEn": "Denmark",
      "lat": 55.966965,
      "lon": 9.018163,
      "minZoom": 3,
      "rank": 4
    },
    {
      "id": "GNQ",
      "isoA2": "GQ",
      "nameEn": "Equatorial Guinea",
      "lat": 2.333,
      "lon": 8.9902,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "ERI",
      "isoA2": "ER",
      "nameEn": "Eritrea",
      "lat": 15.787401,
      "lon": 38.285566,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "SWZ",
      "isoA2": "SZ",
      "nameEn": "Eswatini",
      "lat": -26.533676,
      "lon": 31.467264,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "GAB",
      "isoA2": "GA",
      "nameEn": "Gabon",
      "lat": -0.437739,
      "lon": 11.835939,
      "minZoom": 3,
      "rank": 4
    },
    {
      "id": "GUY",
      "isoA2": "GY",
      "nameEn": "Guyana",
      "lat": 5.124317,
      "lon": -58.942643,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "ISR",
      "isoA2": "IL",
      "nameEn": "Israel",
      "lat": 30.911148,
      "lon": 34.847915,
      "minZoom": 3,
      "rank": 4
    },
    {
      "id": "JAM",
      "isoA2": "JM",
      "nameEn": "Jamaica",
      "lat": 18.137124,
      "lon": -77.318767,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "JOR",
      "isoA2": "JO",
      "nameEn": "Jordan",
      "lat": 30.805025,
      "lon": 36.375991,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "KGZ",
      "isoA2": "KG",
      "nameEn": "Kyrgyzstan",
      "lat": 41.66854,
      "lon": 74.532637,
      "minZoom": 3,
      "rank": 4
    },
    {
      "id": "LAO",
      "isoA2": "LA",
      "nameEn": "Laos",
      "lat": 19.431821,
      "lon": 102.533912,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "LBR",
      "isoA2": "LR",
      "nameEn": "Liberia",
      "lat": 6.447177,
      "lon": -9.460379,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "OMN",
      "isoA2": "OM",
      "nameEn": "Oman",
      "lat": 22.120427,
      "lon": 57.336553,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "PAN",
      "isoA2": "PA",
      "nameEn": "Panama",
      "lat": 8.72198,
      "lon": -80.352106,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "PRY",
      "isoA2": "PY",
      "nameEn": "Paraguay",
      "lat": -21.674509,
      "lon": -60.146394,
      "minZoom": 3,
      "rank": 4
    },
    {
      "id": "COG",
      "isoA2": "CG",
      "nameEn": "Republic of the Congo",
      "lat": 0.142331,
      "lon": 15.9005,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "SLE",
      "isoA2": "SL",
      "nameEn": "Sierra Leone",
      "lat": 8.617449,
      "lon": -11.763677,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "SUR",
      "isoA2": "SR",
      "nameEn": "Suriname",
      "lat": 4.143987,
      "lon": -55.91094,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "CHE",
      "isoA2": "CH",
      "nameEn": "Switzerland",
      "lat": 46.719114,
      "lon": 7.463965,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "TJK",
      "isoA2": "TJ",
      "nameEn": "Tajikistan",
      "lat": 38.199835,
      "lon": 72.587276,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "BHS",
      "isoA2": "BS",
      "nameEn": "The Bahamas",
      "lat": 26.401789,
      "lon": -77.146688,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "TKM",
      "isoA2": "TM",
      "nameEn": "Turkmenistan",
      "lat": 39.855246,
      "lon": 58.676647,
      "minZoom": 3,
      "rank": 4
    },
    {
      "id": "ARE",
      "isoA2": "AE",
      "nameEn": "United Arab Emirates",
      "lat": 23.466285,
      "lon": 54.547256,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "URY",
      "isoA2": "UY",
      "nameEn": "Uruguay",
      "lat": -32.961127,
      "lon": -55.966942,
      "minZoom": 3,
      "rank": 4
    },
    {
      "id": "VUT",
      "isoA2": "VU",
      "nameEn": "Vanuatu",
      "lat": -15.37153,
      "lon": 166.908762,
      "minZoom": 4,
      "rank": 4
    },
    {
      "id": "AZE",
      "isoA2": "AZ",
      "nameEn": "Azerbaijan",
      "lat": 40.402387,
      "lon": 47.210994,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "BEN",
      "isoA2": "BJ",
      "nameEn": "Benin",
      "lat": 10.324775,
      "lon": 2.352018,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "BTN",
      "isoA2": "BT",
      "nameEn": "Bhutan",
      "lat": 27.536685,
      "lon": 90.040294,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "BIH",
      "isoA2": "BA",
      "nameEn": "Bosnia and Herzegovina",
      "lat": 44.091051,
      "lon": 18.06841,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "CRI",
      "isoA2": "CR",
      "nameEn": "Costa Rica",
      "lat": 10.0651,
      "lon": -84.077922,
      "minZoom": 2,
      "rank": 5
    },
    {
      "id": "CYP",
      "isoA2": "CY",
      "nameEn": "Cyprus",
      "lat": 34.913329,
      "lon": 33.084182,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "CZE",
      "isoA2": "CZ",
      "nameEn": "Czech Republic",
      "lat": 49.882364,
      "lon": 15.377555,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "DJI",
      "isoA2": "DJ",
      "nameEn": "Djibouti",
      "lat": 11.976343,
      "lon": 42.498825,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "DOM",
      "isoA2": "DO",
      "nameEn": "Dominican Republic",
      "lat": 19.104137,
      "lon": -70.653998,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "TLS",
      "isoA2": "TL",
      "nameEn": "East Timor",
      "lat": -8.803705,
      "lon": 125.854679,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "FLK",
      "isoA2": "FK",
      "nameEn": "Falkland Islands",
      "lat": -51.608913,
      "lon": -58.738602,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "GEO",
      "isoA2": "GE",
      "nameEn": "Georgia",
      "lat": 41.870087,
      "lon": 43.735724,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "HTI",
      "isoA2": "HT",
      "nameEn": "Haiti",
      "lat": 19.263784,
      "lon": -72.224051,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "HND",
      "isoA2": "HN",
      "nameEn": "Honduras",
      "lat": 14.794801,
      "lon": -86.887604,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "HUN",
      "isoA2": "HU",
      "nameEn": "Hungary",
      "lat": 47.086841,
      "lon": 19.447867,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "LVA",
      "isoA2": "LV",
      "nameEn": "Latvia",
      "lat": 57.066872,
      "lon": 25.458723,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "LBN",
      "isoA2": "LB",
      "nameEn": "Lebanon",
      "lat": 34.133368,
      "lon": 35.992892,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "LTU",
      "isoA2": "LT",
      "nameEn": "Lithuania",
      "lat": 55.103703,
      "lon": 24.089932,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "NLD",
      "isoA2": "NL",
      "nameEn": "Netherlands",
      "lat": 52.422211,
      "lon": 5.61144,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "NIC",
      "isoA2": "NI",
      "nameEn": "Nicaragua",
      "lat": 12.670697,
      "lon": -85.069347,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "PSX",
      "isoA2": "PS",
      "nameEn": "Palestine",
      "lat": 32.047431,
      "lon": 35.291341,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "PRI",
      "isoA2": "PR",
      "nameEn": "Puerto Rico",
      "lat": 18.234668,
      "lon": -66.481065,
      "minZoom": 3,
      "rank": 5
    },
    {
      "id": "QAT",
      "isoA2": "QA",
      "nameEn": "Qatar",
      "lat": 25.237383,
      "lon": 51.143509,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "SRB",
      "isoA2": "RS",
      "nameEn": "Serbia",
      "lat": 44.189919,
      "lon": 20.787989,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "SOL",
      "isoA2": null,
      "nameEn": "Somaliland",
      "lat": 9.443889,
      "lon": 46.731595,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "TTO",
      "isoA2": "TT",
      "nameEn": "Trinidad and Tobago",
      "lat": 10.9989,
      "lon": -60.9184,
      "minZoom": 4,
      "rank": 5
    },
    {
      "id": "ALB",
      "isoA2": "AL",
      "nameEn": "Albania",
      "lat": 40.654855,
      "lon": 20.11384,
      "minZoom": 5,
      "rank": 6
    },
    {
      "id": "ARM",
      "isoA2": "AM",
      "nameEn": "Armenia",
      "lat": 40.459077,
      "lon": 44.800564,
      "minZoom": 5,
      "rank": 6
    },
    {
      "id": "BLZ",
      "isoA2": "BZ",
      "nameEn": "Belize",
      "lat": 17.202068,
      "lon": -88.712962,
      "minZoom": 5,
      "rank": 6
    },
    {
      "id": "BRN",
      "isoA2": "BN",
      "nameEn": "Brunei",
      "lat": 4.448298,
      "lon": 114.551943,
      "minZoom": 4,
      "rank": 6
    },
    {
      "id": "BDI",
      "isoA2": "BI",
      "nameEn": "Burundi",
      "lat": -3.332836,
      "lon": 29.917086,
      "minZoom": 4,
      "rank": 6
    },
    {
      "id": "HRV",
      "isoA2": "HR",
      "nameEn": "Croatia",
      "lat": 45.805799,
      "lon": 16.37241,
      "minZoom": 4,
      "rank": 6
    },
    {
      "id": "SLV",
      "isoA2": "SV",
      "nameEn": "El Salvador",
      "lat": 13.685371,
      "lon": -88.890124,
      "minZoom": 5,
      "rank": 6
    },
    {
      "id": "EST",
      "isoA2": "EE",
      "nameEn": "Estonia",
      "lat": 58.724865,
      "lon": 25.867126,
      "minZoom": 3,
      "rank": 6
    },
    {
      "id": "FJI",
      "isoA2": "FJ",
      "nameEn": "Fiji",
      "lat": -17.826099,
      "lon": 177.975427,
      "minZoom": 3,
      "rank": 6
    },
    {
      "id": "ATF",
      "isoA2": "TF",
      "nameEn": "French Southern and Antarctic Lands",
      "lat": -49.303721,
      "lon": 69.122136,
      "minZoom": 4,
      "rank": 6
    },
    {
      "id": "GNB",
      "isoA2": "GW",
      "nameEn": "Guinea-Bissau",
      "lat": 12.163712,
      "lon": -14.52413,
      "minZoom": 5,
      "rank": 6
    },
    {
      "id": "KOS",
      "isoA2": "XK",
      "nameEn": "Kosovo",
      "lat": 42.593587,
      "lon": 20.860719,
      "minZoom": 5,
      "rank": 6
    },
    {
      "id": "KWT",
      "isoA2": "KW",
      "nameEn": "Kuwait",
      "lat": 29.413628,
      "lon": 47.313999,
      "minZoom": 5,
      "rank": 6
    },
    {
      "id": "LSO",
      "isoA2": "LS",
      "nameEn": "Lesotho",
      "lat": -29.480158,
      "lon": 28.246639,
      "minZoom": 4,
      "rank": 6
    },
    {
      "id": "LUX",
      "isoA2": "LU",
      "nameEn": "Luxembourg",
      "lat": 49.733732,
      "lon": 6.07762,
      "minZoom": 5,
      "rank": 6
    },
    {
      "id": "MWI",
      "isoA2": "MW",
      "nameEn": "Malawi",
      "lat": -13.386737,
      "lon": 33.608082,
      "minZoom": 4,
      "rank": 6
    },
    {
      "id": "MDA",
      "isoA2": "MD",
      "nameEn": "Moldova",
      "lat": 47.434999,
      "lon": 28.487904,
      "minZoom": 5,
      "rank": 6
    },
    {
      "id": "MNE",
      "isoA2": "ME",
      "nameEn": "Montenegro",
      "lat": 42.803101,
      "lon": 19.143727,
      "minZoom": 5,
      "rank": 6
    },
    {
      "id": "MKD",
      "isoA2": "MK",
      "nameEn": "North Macedonia",
      "lat": 41.558223,
      "lon": 21.555839,
      "minZoom": 5,
      "rank": 6
    },
    {
      "id": "SVK",
      "isoA2": "SK",
      "nameEn": "Slovakia",
      "lat": 48.734044,
      "lon": 19.049868,
      "minZoom": 4,
      "rank": 6
    },
    {
      "id": "SVN",
      "isoA2": "SI",
      "nameEn": "Slovenia",
      "lat": 46.06076,
      "lon": 14.915312,
      "minZoom": 5,
      "rank": 6
    },
    {
      "id": "SOM",
      "isoA2": "SO",
      "nameEn": "Somalia",
      "lat": 3.568925,
      "lon": 45.19238,
      "minZoom": 4,
      "rank": 6
    },
    {
      "id": "GMB",
      "isoA2": "GM",
      "nameEn": "The Gambia",
      "lat": 13.641721,
      "lon": -14.998318,
      "minZoom": 5,
      "rank": 6
    },
    {
      "id": "TGO",
      "isoA2": "TG",
      "nameEn": "Togo",
      "lat": 8.80722,
      "lon": 1.058113,
      "minZoom": 5,
      "rank": 6
    },
    {
      "id": "CYN",
      "isoA2": null,
      "nameEn": "Turkish Republic of Northern Cyprus",
      "lat": 35.216071,
      "lon": 33.692434,
      "minZoom": 6,
      "rank": 6
    },
    {
      "id": "SAH",
      "isoA2": "EH",
      "nameEn": "Western Sahara",
      "lat": 23.967592,
      "lon": -12.630304,
      "minZoom": 6,
      "rank": 7
    }
  ],
  "marine": [
    {
      "id": "Q788-0",
      "nameEn": "Arctic Ocean",
      "nameNo": "Polhavet",
      "lat": 80.60421,
      "lon": -0.00005,
      "minZoom": 1,
      "maxZoom": 7,
      "rank": 0
    },
    {
      "id": "Q97-0",
      "nameEn": "Atlantic Ocean",
      "nameNo": "Atlanterhavet",
      "lat": 34.22972,
      "lon": -37.48179,
      "minZoom": 1,
      "maxZoom": 7,
      "rank": 0
    },
    {
      "id": "Q97-1",
      "nameEn": "Atlantic Ocean",
      "nameNo": "Atlanterhavet",
      "lat": -30.2503,
      "lon": -24.72861,
      "minZoom": 1,
      "maxZoom": 7,
      "rank": 0
    },
    {
      "id": "Q1239-0",
      "nameEn": "Indian Ocean",
      "nameNo": "Indiahavet",
      "lat": -25.05123,
      "lon": 92.84111,
      "minZoom": 1,
      "maxZoom": 7,
      "rank": 0
    },
    {
      "id": "Q98-0",
      "nameEn": "Pacific Ocean",
      "nameNo": "Stillehavet",
      "lat": 25,
      "lon": -155,
      "minZoom": 1,
      "maxZoom": 7,
      "rank": 0
    },
    {
      "id": "Q98-1",
      "nameEn": "Pacific Ocean",
      "nameNo": "Stillehavet",
      "lat": -27,
      "lon": -140,
      "minZoom": 1,
      "maxZoom": 7,
      "rank": 0
    },
    {
      "id": "Q7354-0",
      "nameEn": "Southern Ocean",
      "nameNo": "Sørishavet",
      "lat": -66.39636,
      "lon": -0.00005,
      "minZoom": 1,
      "maxZoom": 7,
      "rank": 0
    },
    {
      "id": "Q58705-0",
      "nameEn": "Arabian Sea",
      "nameNo": "Arabiahavet",
      "lat": 12.4606,
      "lon": 62.68892,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q37040-0",
      "nameEn": "Baffin Bay",
      "nameNo": "Baffinbukta",
      "lat": 74.28367,
      "lon": -68.16156,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q38684-0",
      "nameEn": "Bay of Bengal",
      "nameNo": "Bengalbukta",
      "lat": 14.55663,
      "lon": 87.46423,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q131274-0",
      "nameEn": "Beaufort Sea",
      "nameNo": "Beauforthavet",
      "lat": 72.7922,
      "lon": -139.53635,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q166-0",
      "nameEn": "Black Sea",
      "nameNo": "Svartehavet",
      "lat": 44.06878,
      "lon": 34.62376,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q1247-0",
      "nameEn": "Caribbean Sea",
      "nameNo": "Det karibiske hav",
      "lat": 15.59141,
      "lon": -73.77893,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q5484-0",
      "nameEn": "Caspian Sea",
      "nameNo": "Det kaspiske hav",
      "lat": 41.86243,
      "lon": 50.36543,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q82931-0",
      "nameEn": "Coral Sea",
      "nameNo": "Korallhavet",
      "lat": -19.40951,
      "lon": 156.30801,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q180531-0",
      "nameEn": "Gulf of Alaska",
      "nameNo": "Alaskabukta",
      "lat": 57.35854,
      "lon": -149.98686,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q12630-0",
      "nameEn": "Gulf of Mexico",
      "nameNo": "Mexicogolfen",
      "lat": 25.74718,
      "lon": -88.87657,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q3040-0",
      "nameEn": "Hudson Bay",
      "nameNo": "Hudsonbukta",
      "lat": 60.36156,
      "lon": -85.73835,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q184189-0",
      "nameEn": "Labrador Sea",
      "nameNo": "Labradorsjøen",
      "lat": 53.88986,
      "lon": -54.35612,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q4918-0",
      "nameEn": "Mediterranean Sea",
      "nameNo": "Middelhavet",
      "lat": 37.32854,
      "lon": 17.04856,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q34675-0",
      "nameEn": "Persian Gulf",
      "nameNo": "Persiabukten",
      "lat": 27.2405,
      "lon": 52.46303,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q159183-0",
      "nameEn": "Philippine Sea",
      "nameNo": "Filippinerhavet",
      "lat": 18.87278,
      "lon": 133.56392,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q23406-0",
      "nameEn": "Red Sea",
      "nameNo": "Rødehavet",
      "lat": 20.29598,
      "lon": 38.65868,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q164466-0",
      "nameEn": "Ross Sea",
      "nameNo": "Rosshavet",
      "lat": -76,
      "lon": 175,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q27092-0",
      "nameEn": "Sea of Japan",
      "nameNo": "Japanhavet",
      "lat": 43.09281,
      "lon": 135.26043,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q41602-0",
      "nameEn": "Sea of Okhotsk",
      "nameNo": "Okhotskhavet",
      "lat": 51.52501,
      "lon": 147.17885,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q37660-0",
      "nameEn": "South China Sea",
      "nameNo": "Sør-Kina-havet",
      "lat": 10.27012,
      "lon": 112.30757,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q33254-0",
      "nameEn": "Tasman Sea",
      "nameNo": "Tasmanhavet",
      "lat": -40.33382,
      "lon": 160.80727,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    },
    {
      "id": "Q173343-0",
      "nameEn": "Weddell Sea",
      "nameNo": "Weddellhavet",
      "lat": -77.29559,
      "lon": -47.36874,
      "minZoom": 2,
      "maxZoom": 8,
      "rank": 1
    }
  ]
} as const;
